### ISSUE TITLE
Binary file

### ISSUE THREAD

**Issue by metanovii** [ClickHouse/clickhouse_exporter#32]
Hi, can u make precompiled binary file  ?

**Comment by k0st1an** [comment]
+1

**Comment by alexqrid** [comment]
@Slach This is super actual, especially when you setup monitoring using configuration management tools (`Ansible`,`Chef`, `Puppet` etc.), most of the prometheus exporters have a pre-build binaries like [node-exporter](https://github.com/prometheus/node_exporter/releases/tag/v1.3.1) that saves hundreds lines of code in configuration management. Can you add a pre-build binary for `linux-amd64`  at least, please?

**Comment by Slach** [comment]
@alexqrid clickhouse itself already have embedded prometheus endpoint
you don't need clickhouse-exporter for new versions of clickhouse
