### ISSUE TITLE
Doesn't work with latest version of CH

### ISSUE THREAD

**Issue by ajardan** [ClickHouse/clickhouse_exporter#39]
We are running CH 19.06.02 and it seems they added a description column in the system.metrics table, which breaks this:

https://github.com/f1yegor/clickhouse_exporter/blob/fc3a55668dd7011d30336c3114c9dcfba9c2cf56/exporter/exporter.go#L224

since length is 3 now.

**Comment by f1yegor** [comment]
Solved in master
