### ISSUE TITLE
CentOS7 go install Problems arise

### ISSUE THREAD

**Issue by yd1261137568** [ClickHouse/clickhouse_exporter#41]
[root@iznpqe8ynbddhpz clickhouse_exporter-master]# go install 
clickhouse_exporter.go:9:2: cannot find package "github.com/f1yegor/clickhouse_exporter/exporter" in any of:
	/opt/soft/gopath/src/github.com/clickhouse_exporter-master/vendor/github.com/f1yegor/clickhouse_exporter/exporter (vendor tree)
	/opt/soft/go/src/github.com/f1yegor/clickhouse_exporter/exporter (from $GOROOT)
	/opt/soft/gopath/src/github.com/f1yegor/clickhouse_exporter/exporter (from $GOPATH)

**Comment by f1yegor** [comment]
Solved in master
