### ISSUE TITLE
cannot parse Float type

### ISSUE THREAD

**Issue by 1160300616** [ClickHouse/clickhouse_exporter#44]
Hello, I found a bug in the code.
Metrics in system.asynchronous_ values may not be of Int type, but may also be of Float type.
If the code is not modified, when a value of float type appears in metrics, the following problems will occur:

Error scraping clickhouse url  http://xxx :8123/?query=select+metric%2C+value+from+ system.asynchronous_ metrics:  strconv.Atoi : parsing "2199.998": invalid syntax  file= exporter.go  line=292

After the code in exporter.go is modified as follows, the problem is solved
q.Set("query", "select metric, value from  system.asynchronous_ metrics") -> q.Set("query", "select metric, toInt64(value) from  system.asynchronous_ metrics")

**Comment by f1yegor** [comment]
Fix in master. Thanks for reporting
