### ISSUE TITLE
Difference between this and the one provided with Clickhouse itself?

### ISSUE THREAD

**Issue by fzyzcjy** [ClickHouse/clickhouse_exporter#45]
Hi I wonder the difference between this and https://clickhouse.tech/docs/en/operations/monitoring/ (ie https://clickhouse.tech/docs/en/operations/server-configuration-parameters/settings/#server_configuration_parameters-prometheus)?

**Comment by Slach** [comment]
this provider is much older than the embedded clickhouse-server endpoint for Prometheus, we will going to try customize this, to allow produce metrics with a compatible format with the embedded endpoint

**Comment by fzyzcjy** [comment]
@Slach So do you suggest me to use the embedded one or this repo?

**Comment by Slach** [comment]
@fzyzcjy please use embedded Prometheus endpoint for the new clickhouse versions

**Comment by fzyzcjy** [comment]
@Slach Thanks
