### ISSUE TITLE
Floating point number resolution failed

### ISSUE THREAD

**Issue by lihuanbby** [ClickHouse/clickhouse_exporter#53]
Hi,I have this problem
time="2021-03-01T07:49:19Z" level=info msg="Error scraping clickhouse: Error scraping clickhouse url http://localhost:8123?query=select+metric%2C+value+from+system.asynchronous_metrics: strconv.Atoi: parsing \"2095.078\": invalid syntax" file=exporter.go line=292 .

Floating point number resolution failed, how to solve it. thanks

**Comment by jwoglom** [comment]
I think this is fixed in #52.

**Comment by Slach** [comment]
yep it fixed on latest master, i close issue
