### ISSUE TITLE
programe has a exporter but import github.com/Percona-Lab/clickhouse_exporter/exporter

### ISSUE THREAD

**Issue by Yanbuc** [ClickHouse/clickhouse_exporter#56]
the program has a exporter but import github.com/Percona-Lab/clickhouse_exporter/exporter
the github.com/Percona-Lab/clickhouse_exporter/exporter not fix float bug. To see the code in github.com/Percona-Lab/clickhouse_exporter/exporter , it doesn't have parseNumber() and exporter in the program has the parseNumber()

**Comment by Slach** [comment]
fixed on latest `master`
