### ISSUE TITLE
How to monitor whole ClickHouse cluster?

### ISSUE THREAD

**Issue by juexinformac** [ClickHouse/clickhouse_exporter#64]
How to monitor whole ClickHouse cluster? Like node exporter, Start agent in all Cluster nodes?

**Comment by Slach** [comment]
try to use `telegraf` clickhouse plugin https://github.com/influxdata/telegraf/tree/master/plugins/inputs/clickhouse

or if you use kubernetes + clickhouse-operator
use internal clickhouse-operator metrics exporter
