### ISSUE TITLE
 is not a valid metric name   

### ISSUE THREAD

**Issue by 37705109** [ClickHouse/clickhouse_exporter#70]
panic: descriptor Desc{fqName: "clickhouse_block_discard_ops_dm-0", help: "Number of BlockDiscardOps_dm-0 async processed", constLabels: {}, variableLabels: []} is invalid: "clickhouse_block_discard_ops_dm-0" is not a valid metric name

clickhouse-server 22.2.2.1

**Comment by Slach** [comment]
use embedded prometheus endpoint
https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings/#server_configuration_parameters-prometheus

and https://grafana.com/grafana/dashboards/13500

look details
https://kb.altinity.com/altinity-kb-setup-and-maintenance/altinity-kb-monitoring/

**Comment by xythotmail** [comment]
good!
