### ISSUE TITLE
I found a bug where rancher would run and go would return an error

### ISSUE THREAD

**Issue by lixianseng-limeidong** [ClickHouse/clickhouse_exporter#76]
The specific error is as follows:
panic: descriptor Desc{fqName: "clickhouse_block_write_time_dm-0", help: "Number of BlockWriteTime_dm-0 async processed", constLabels: {}, variableLabels: []} is invalid: "clickhouse_block_write_time_dm-0" is not a valid metric name

It seems to be caused by the index hyphen in clickhouse. Is there a problem with the last submission? Check and see that the hyphen of one index was not replaced

When pure docker runs, all indicators can be replaced normally, but k8s seems not to be replaced normally, which is strange

**Comment by Slach** [comment]
use embedded prometheus endpoint instead of this outdated exporter

https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#server_configuration_parameters-prometheus
