### ISSUE TITLE
exec /usr/local/bin/clickhouse_exporter: no such file or directory

### ISSUE THREAD

**Issue by kuverus** [ClickHouse/clickhouse_exporter#84]
I built container
```
docker build --tag myrepo/clickhouse-exporter:latest .
```

But got an error on running
```
docker run -ti myrepo/clickhouse-exporter:latest
exec /usr/local/bin/clickhouse_exporter: no such file or directory
```

After some digging, I found the binary is dynamically linked:
```
~ $ ldd /usr/local/bin/clickhouse_exporter
        /lib64/ld-linux-x86-64.so.2 (0x7f2b1739c000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f2b1739c000)
```
and alpine have non-standard libc - https://stackoverflow.com/questions/66963068/docker-alpine-executable-binary-not-found-even-if-in-path

So my solution:
```
apk add libc6-compat 
```

**Comment by Slach** [comment]
please use embedded prometheus endpoint instead of this exporter https://clickhouse.com/docs/en/operations/server-configuration-parameters/settings#prometheus
